select  *  from   specMS_ChangeControl_Apply
select  *  from   specMS_Deliverables
select  *  from   specMS_Character
select  *  from   specMS_EntryDepend
select  *  from   specMS_PredefineParam
select  *  from   specMS_Read_Apply
select  *  from   specMS_SpecEditor
select  *  from   specMS_SpecList
select  *  from   specMS_SpecModule