--ÒÑÖ´ÐÐ
--update   RecruitReqApply    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   PersonSubmitApproval    set   ModificationDate=GETDATE()  where  ModificationDate  is  null or  ModificationDate='1900-01-01';
--update   ProjectSetup    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   PayReport    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ExpenseSettlementDetail    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';

--Î´Ö´ÐÐ
--update   PersonEntry    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   PersonInfo    set   ModificationDate=GETDATE()  where  ModificationDate  is  null or  ModificationDate='1900-01-01';
--update   PersonEvaluate    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   TraineeThesis    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   TraineeCertificate    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectSetup    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   AskForLeave    set   ModificationDate=GETDATE()  where  ModificationDate  is  null or  ModificationDate='1900-01-01';
--update   AskForOvertime    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   AbnormalRecord    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectSummary    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectExceptionEnd    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectPersonEntry    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectPersonInfo    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectPersonEvaluate    set   ModificationDate=GETDATE()  where  ModificationDate  is  null  or  ModificationDate='1900-01-01';
--update   ProjectCheckReport    set   ModifierTime=GETDATE()  where  ModifierTime  is  null  or  ModifierTime='1900-01-01';
