USE [hrcp]
GO

/****** Object:  View [dbo].[V_ProjectPersonInfo]    Script Date: 2019/10/25 18:19:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER view [dbo].[V_ProjectPersonInfo]
as 
select pinfo.ProjectPersonInfoId,
       pinfo.Name,
       pinfo.IdCard,
       pinfo.Sex,
       pinfo.CooCompany,
       pinfo.ProjectName,
       pinfo.ProjectCode,
       pinfo.ApplyType,
       pinfo.ProjectMgr,
       pinfo.CooMgr,
       pinfo.EntryDate,
       pinfo.ExpiryDate,
       pinfo.IsInField,
       pinfo.Area,
       pinfo.ApplyEntryArea,
       pinfo.LeaveDate,
       pinfo.DirectMgr,
       pinfo.EvaluateMgr,
       pinfo.IsApplyId,
       pinfo.ID,
       pinfo.InfoSaveCheck,
       pinfo.CheckResult,
       pinfo.CreateBy,
       pinfo.CreateDate,
       pinfo.ModificationDate,
       pinfo.Modifier,
       pinfo.DeleteFlag,
       pinfo.CooType,
       pinfo.IsOnDuty,
       pinfo.WorkPlace,
       pinfo.PositionName,
       pinfo.Native,
       pinfo.Nation,
       pinfo.PoliticalStatus,
       pinfo.Marriage,
       pinfo.Education,
       pinfo.Major,
       pinfo.BirthDay,
       pinfo.Graduated,
       pinfo.PhysicalExamination,
       pinfo.PersonalSecrecyAgreement,
       pinfo.ApplyRemark,
       pinfo.ApplySign,
       pinfo.ApplySignDate,
       pinfo.DocCheckClose,
       pinfo.DocCheckCloseRemark,
       pinfo.DocCheckIsDone,
       pinfo.DocCheckSign,
       pinfo.DocCheckSignDate,
       pinfo.PcLow,
       pinfo.PcSpecial,
       pinfo.BorrowStorage,
       pinfo.InfoSafeRemark,
       pinfo.InfoSafeIsDone,
       pinfo.InfoSafeSign,
       pinfo.InfoSafeSignDate,
       pinfo.Pc,
       pinfo.AssetMgrIsDone,
       pinfo.AssetMgrRemark,
       pinfo.AssetMgrSign,
       pinfo.AssetMgrSignDate,
       pinfo.DocMove,
       pinfo.FileDoc,
       pinfo.MaterialReturn,
       pinfo.WorkCard,
       pinfo.NotesDomainCancle,
       pinfo.PdmCancle,
       pinfo.PermissionCancleRemark,
       pinfo.PermissionCancleSign,
       pinfo.PermissionCancleSignDate,
       pinfo.PermissionCancleIsDone,
       pinfo.DoorCancle,
       pinfo.DoorCancleRemark,
       pinfo.DoorCancleIsDone,
       pinfo.DoorCancleSign,
       pinfo.DoorCancleSignDate,
       pinfo.CardConfirm,
       pinfo.CardConfirmStatus,
       pinfo.CardConfirmIsDone,
       pinfo.CardConfirmSign,
       pinfo.CardConfirmSignDate,
       pinfo.PdmConfirm,
       pinfo.PdmConfirmStatus,
       pinfo.PdmConfirmIsDone,
       pinfo.PdmConfirmSign,
       pinfo.PdmConfirmSignDate,
       pinfo.PersonStatus,
       pinfo.ArchiveTime,
       pinfo.ReleaseTime,
       pinfo.LeaveType,
       pinfo.DirectorMgrSign,
       pinfo.DirectorMgrSignDate,
       pinfo.CooLeaveType,
       pinfo.CooMgrSign,
       pinfo.CooMgrSignDate,
       pinfo.PositionLevel,
       pinfo.ProjectType,
       pinfo.AttendanceClass,
       pinfo.IsTurnNext,
       pinfo.IsFinishFile,
       pinfo.IsWarn,
       pinfo.FirstEntryDate,
       pinfo.ProDirector,
       pinfo.ReleaseType,
       pinfo.ProMgrReleaseDate,
       pinfo.AgreeStartDate,
       pinfo.AgreeEndDate,
       pinfo.PlanEndDate,
       pinfo.DirectorCc,
       pinfo.CooMgrCc,
       pinfo.DocCheckCc,
       pinfo.InfoSafeCc,
       pinfo.AssetMgrCc,
       pinfo.PermissionCancleCc,
       pinfo.DoorCancleCc,
       pinfo.ReceiptCc,
       pinfo.LeaveFieldDate,
       pinfo.ReleaseOpinion,
       pinfo.PreStartDate,
       pinfo.PreEndDate,
	   pinfo.CardConfirmOpinion,
       pinfo.IsSignLeave,
	   D1.Name AS DeptLevel1,pinfo.DeptCode1,D2.Name AS DeptLevel2,pinfo.DeptCode2,D3.Name AS DeptLevel3,pinfo.DeptCode3,
	   pf.ProcessFlowId,pf.WorkFlowInstanceId,pf.CurrentPerson,pf.CurrentNode,wfi.States,pr.DocAdminSureEntryDataSign AS EntryFile,pr.DocAdminSureReleaseDataSign AS LeaveFile
from V_ProjectPersonInfo_ALL pinfo inner join ProcessFlow pf on pinfo.ProjectPersonInfoId=pf.ApprovalId inner join WorkFlowInstance wfi on wfi.WorkFlowInstanceId=pf.WorkFlowInstanceId 
left join ProjectPersonRecord pr on pr.ProjectPersonInfoId=pinfo.ProjectPersonInfoId  
LEFT JOIN Department D2 ON D2.Code=pinfo.DeptCode2
LEFT JOIN Department d1 ON d1.Code=pinfo.DeptCode1
LEFT JOIN Department d3 ON d3.Code=pinfo.DeptCode3
WHERE pinfo.DeleteFlag=0



GO


