
--按部门
--exec sp_executesql N'EXEC [dbo].[P_WorkHourDeptView_New]  @startDate,@endDate,@ProjectLevel,@groupBySql,@whereSql,@groupByProductNoDeptSql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary,@projectCode,@proTreeNode,@deptTreeNode,@RowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(105),@whereSql nvarchar(99),@groupByProductNoDeptSql nvarchar(73),@conditionFlag nvarchar(5),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@RowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  SecondDeptName,SecondDeptCode,ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@whereSql=N' where  ProductLineCode=sp.ProductLineCode and PDTCode=sp.PDTCode and BVersionCode=sp.BVersionCode ',@groupByProductNoDeptSql=N'ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'',@RowID=N'',@pageIndex=1,@pageCount=15

--exec sp_executesql N'EXEC [dbo].[P_WorkHourDeptView_Test]  @startDate,@endDate,@ProjectLevel,@groupBySql,@whereSql,@groupByProductNoDeptSql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary,@projectCode,@proTreeNode,@deptTreeNode,@RowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(105),@whereSql nvarchar(99),@groupByProductNoDeptSql nvarchar(73),@conditionFlag nvarchar(5),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@RowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  SecondDeptName,SecondDeptCode,ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@whereSql=N' where  ProductLineCode=sp.ProductLineCode and PDTCode=sp.PDTCode and BVersionCode=sp.BVersionCode ',@groupByProductNoDeptSql=N'ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'',@RowID=N'',@pageIndex=1,@pageCount=15

--二级部门筛选
--exec sp_executesql N'EXEC [dbo].[P_WorkHourDeptView_New]  @startDate,@endDate,@ProjectLevel,@groupBySql,@whereSql,@groupByProductNoDeptSql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary,@projectCode,@proTreeNode,@deptTreeNode,@RowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(105),@whereSql nvarchar(99),@groupByProductNoDeptSql nvarchar(73),@conditionFlag nvarchar(5),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(171),@RowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  SecondDeptName,SecondDeptCode,ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@whereSql=N' where  ProductLineCode=sp.ProductLineCode and PDTCode=sp.PDTCode and BVersionCode=sp.BVersionCode ',@groupByProductNoDeptSql=N'ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'50041390,50041391,50041593,50041594,50041392,50041597,50041393,50041599,50041600,50041394,50041602,50041603,50041395,50041605,50041606,50041607,50041396,50041608,50041610,',@RowID=N'',@pageIndex=1,@pageCount=15
--测试中心
exec sp_executesql N'EXEC [dbo].[P_WorkHourDeptView_New]  @startDate,@endDate,@ProjectLevel,@groupBySql,@whereSql,@groupByProductNoDeptSql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary,@projectCode,@proTreeNode,@deptTreeNode,@RowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(105),@whereSql nvarchar(99),@groupByProductNoDeptSql nvarchar(73),@conditionFlag nvarchar(5),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(54),@RowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  SecondDeptName,SecondDeptCode,ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@whereSql=N' where  ProductLineCode=sp.ProductLineCode and PDTCode=sp.PDTCode and BVersionCode=sp.BVersionCode ',@groupByProductNoDeptSql=N'ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'50041371,50041372,50041373,50041374,50041375,50043439,',@RowID=N'',@pageIndex=1,@pageCount=15

--按人力投入总表

--exec sp_executesql N'EXEC [dbo].[P_WorkHourSummaryView_New]  @startDate,@endDate,@ProjectLevel,@GroupBySql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary, @projectCode, @proTreeNode, @deptTreeNode,@rowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(75),@conditionFlag nvarchar(8),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@rowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7,8,',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'',@rowID=N'',@pageIndex=1,@pageCount=15

--去除or

--exec sp_executesql N'EXEC [dbo].[P_WorkHourSummaryView_Test]  @startDate,@endDate,@ProjectLevel,@GroupBySql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary, @projectCode, @proTreeNode, @deptTreeNode,@rowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(75),@conditionFlag nvarchar(8),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@rowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2019-11-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7,8,',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=1,@sysDeptManager=1,@sysDeptSecretary=1,@projectCode=N'A18001M',@proTreeNode=N'',@deptTreeNode=N'',@rowID=N'',@pageIndex=1,@pageCount=15

--月统计存储过程
exec sp_executesql N'exec P_PersonalMonthView @Code,@month,@ProjectLevel,@conditionFlag,@date,@projectCode,@proTreeNode',N'@Code nvarchar(5),@month nvarchar(7),@ProjectLevel nvarchar(1),@conditionFlag nvarchar(8),@date nvarchar(4000),@projectCode nvarchar(4000),@proTreeNode nvarchar(4000)',@Code=N'03806',@month=N'2020-01',@ProjectLevel=N'4',@conditionFlag=N'2,3,4,5,',@date=N'',@projectCode=N'',@proTreeNode=N''

--dumin
exec sp_executesql N'EXEC [dbo].[P_WorkHourSummaryView]  @startDate,@endDate,@ProjectLevel,@GroupBySql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary, @projectCode, @proTreeNode, @deptTreeNode,@rowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(75),@conditionFlag nvarchar(8),@UserId nvarchar(11),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@rowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2020-01-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7,8,',@UserId=N'dumin 00933',@sysRole=0,@sysProjectManager=1,@sysPoP=0,@sysDeptManager=1,@sysDeptSecretary=0,@projectCode=N'',@proTreeNode=N'',@deptTreeNode=N'',@rowID=N'',@pageIndex=1,@pageCount=15

--liucaixuan   
exec sp_executesql N'EXEC [dbo].[P_WorkHourSummaryView]  @startDate,@endDate,@ProjectLevel,@GroupBySql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary, @projectCode, @proTreeNode, @deptTreeNode,@rowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(75),@conditionFlag nvarchar(8),@UserId nvarchar(16),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(4000),@proTreeNode nvarchar(8),@deptTreeNode nvarchar(4000),@rowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2020-01-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7,8,',@UserId=N'liucaixuan 03806',@sysRole=1,@sysProjectManager=1,@sysPoP=0,@sysDeptManager=1,@sysDeptSecretary=0,@projectCode=N'',@proTreeNode=N'PT000076',@deptTreeNode=N'',@rowID=N'',@pageIndex=1,@pageCount=15


exec sp_executesql N'EXEC [dbo].[P_WorkHourSummaryView]  @startDate,@endDate,@ProjectLevel,@GroupBySql,@conditionFlag,@UserId,@sysRole,@sysProjectManager,@sysPoP,@sysDeptManager,@sysDeptSecretary, @projectCode, @proTreeNode, @deptTreeNode,@rowID,@pageIndex,@pageCount',N'@startDate datetime,@endDate datetime,@ProjectLevel nvarchar(6),@GroupBySql nvarchar(75),@conditionFlag nvarchar(8),@UserId nvarchar(11),@sysRole int,@sysProjectManager int,@sysPoP int,@sysDeptManager int,@sysDeptSecretary int,@projectCode nvarchar(7),@proTreeNode nvarchar(4000),@deptTreeNode nvarchar(4000),@rowID nvarchar(4000),@pageIndex int,@pageCount int',@startDate='2020-01-01 00:00:00',@endDate='2020-01-31 00:00:00',@ProjectLevel=N'Normal',@GroupBySql=N'  ProductLineCode,ProductLineName,PDTCode,PDTName,BVersionCode,BVersionName',@conditionFlag=N'5,6,7,8,',@UserId=N'dumin 00933',@sysRole=0,@sysProjectManager=1,@sysPoP=0,@sysDeptManager=1,@sysDeptSecretary=0,@projectCode=N'9200028',@proTreeNode=N'',@deptTreeNode=N'',@rowID=N'',@pageIndex=1,@pageCount=15






