select                                                                           
PersonInfoId	           as  	person_infoid	                --主键               
,EmployeeName	           as  	emp_name	                --姓名               
,EntryDate	             as  	entry_date	                  --入职日期           
,NativePlace	           as  	native_place	                --籍贯               
,Nation	                 as  	nation	                      --民族               
,PoliticalLandscape	     as  	political_landscape	          --政治面貌           
,MatricalStatus	         as  	matrical_status	              --婚姻状况           
,TopEducation	           as  	stu_exp_name	                --最高学历           
,Discipline	             as  	spec_type_name	                  --专业   
,case when Sex='0' then '男'else '女' end as sex	              --性别               
,IDCard	                 as  	id_card	                      --身份证号           
,BirthDay	               as  	birthday_date	                    --生日               
,GraduateSchool	         as  	graduate_school	              --毕业学校           
,CooCompany	             as  	coo_company	                  --合作公司名称       
,WorkPlace	             as  	work_place	                  --工作地             
,CooType	               as  	coo_type	                    --合作类别           
,PositionName	           as  	position_name	                --岗位类别           
,rtrim(ltrim(WorkNum))	               as  	emp_code	                    --5位工号            
,rtrim(ltrim(lower(NotesId)))as  	notes_id	                    --notesid            
,Dept2Level	             as  	dept2_code	                  --二级部门编码       
,Dept3Level	             as  	dept3_code                  --三级部门编码       
,DirectorMgrName	       as  	director	            --直接主管姓名       
,RIGHT(DirectorMgrId,5)         as  director_code	              --直接主管id         
,EvaluateMgrId	         as  	evaluate_mgrid	              --考评主管id         
,EvaluateMgrName	       as  	evaluate_mgr_name	            --考评主管姓名       
,TutorId	               as  	tutor_id	                    --导师id             
,TutorName	             as  	tutor_name	                  --导师姓名           
,Telephone	             as  	mobile	                    --电话               
,OfficeLocation	         as  	office_location	              --办公地点           
,DeptSecretaryId	       as  	dept_secretary_id	            --秘书id             
,DeptSecretaryName	     as  	dept_secretary_name	          --秘书姓名           
,Remark	                 as  	remark	                      --备注               
,OnJobStatus	           as  	emp_status	                --是否在职           
,CurrentLevel	           as  	position_level	                --目前在岗级别       
,PositionType	           as  	position_type	                --工程师类别         
,EntryType	             as  	entry_type	                  --入项类别           
,ProEntryDate	           as  	pro_entry_date	              --项目入项日期       
,DeptLevel1	             as  	dept1_code                  --一级部门编码       
,DeptLevel4	             as  	dept4_code	                  --四级部门编码       
,FirstEducation	         as  	first_education	              --第一学历           
,MaterialFileId	         as  	material_fileid	              --离项归档材料附件   
,InterviewFile	         as  	interview_file	              --外包项目人员测评   
,InterviewFileDate	     as  	interview_file_date	          --归档时间           
,InterviewExpDate	       as  	interview_exp_date	          --失效时间           
,InterviewSign	         as  	interview_sign	              --签名               
,InterviewSignDate	     as  	interview_sign_date	          --时间               
,InterviewRemark	       as  	interview_remark	            --备注               
,WrittenFile	           as  	written_file	                --笔试答题纸,归档情  
,WrittenFileDate	       as  	written_file_date	            --归档时间           
,WrittenExpDate	         as  	written_exp_date	            --失效时间           
,WrittenSign	           as  	written_sign	                --签名               
,WrittenSignDate	       as  	written_sign_date	            --时间               
,WrittenRemark	         as  	written_remark	              --备注               
,PersonalAgreeFile	     as  	personal_agree_file	          --个人保密承诺书,归  
,PersonalAgreeFileDate	 as  	personal_agree_file_date	    --归档时间           
,PersonalAgreeExpDate	   as  	personal_agree_exp_date	      --失效时间           
,PersonalAgreeSign	     as  	personal_agree_sign	          --签名               
,PersonalAgreeSignDate	 as  	personal_agree_sign_date	    --时间               
,PersonalAgreeRemark	   as  	personal_agree_remark	        --备注               
,ItAgreeFile	           as  	itagree_file	                --IT资源承诺书       
,ItAgreeFileDate	       as  	itagree_file_date	            --归档时间           
,ItAgreeExpDate	         as  	itagree_exp_date	            --失效时间           
,ItAgreeSign	           as  	it_agree_sign	                --签名               
,ItAgreeSignDate	       as  	it_agree_sign_date	          --时间               
,ItAgreeRemark	         as  	it_agree_remark	              --备注               
,PhysicalCopyFile	       as  	physical_copy_file	          --体检报告复印件     
,PhysicalCopyFileDate	   as  	physical_copy_file_date	      --归档时间           
,PhysicalCopyExpDate	   as  	physical_copy_exp_date	      --失效时间           
,PhysicalCopySign	       as  	physical_copy_sign	          --签名               
,PhysicalCopySignDate	   as  	physical_copy_sign_date	      --时间               
,PhysicalCopyRemark	     as  	physical_copy_remark	        --备注               
,IdCardCopyFile	         as  	idcard_copy_file	            --身份证复印件       
,IdCardCopyFileDate	     as  	id_card_copy_file_date	      --归档时间           
,IdCardCopyExpDate	     as  	id_card_copy_exp_date	        --失效时间           
,IdCardCopySign	         as  	id_card_copy_sign	            --签名               
,IdCardCopySignDate	     as  	id_card_copy_sign_date	      --时间               
,IdCardCopyRemark	       as  	id_card_copy_remark	          --备注               
,CvCopyFile	             as  	cv_copy_file	                --简历/实习生报名表  
,CvCopyFileDate	         as  	cv_copy_file_date	            --归档时间           
,CvCopyExpDate	         as  	cv_copy_exp_date	            --失效时间           
,CvCopySign	             as  	cv_copy_sign	                --签名               
,CvCopySignDate	         as  	cv_copy_sign_date	            --时间               
,CvCopyRemark	           as  	cv_copy_remark	              --备注               
,GraduateCopyFile	       as  	graduate_copy_file	          --毕业证学位证复印   
,GraduateCopyFileDate	   as  	graduate_copy_file_date	      --归档时间           
,GraduateCopyExpDate	   as  	graduate_copy_exp_date	      --失效时间           
,GraduateCopySign	       as  	graduate_copy_sign	          --签名               
,GraduateCopySignDate	   as  	graduate_copy_sign_date	      --时间               
,GraduateCopyRemark	     as  	graduate_copy_remark	        --备注               
,LeaveAgreeFile	         as  	leave_agree_file	            --离项承诺书         
,LeaveAgreeFileDate	     as  	leave_agree_file_date	        --归档时间           
,LeaveAgreeExpDate	     as  	leave_agree_exp_date	        --失效时间           
,LeaveAgreeSign	         as  	leave_agree_sign	            --签名               
,LeaveAgreeSignDate	     as  	leave_agree_sign_date	        --时间               
,LeaveAgreeRemark	       as  	leave_agree_remark	          --备注               
,AttachUrl	             as  	attach_url	                  --归档材料附件url    
,MaterialFileNo	         as  	material_file_no	            --材料归档编号       
,FileStatus	             as  	file_status	                  --状态               
,AttachLeaveUrl	         as  	attach_leave_url	            --离项归档材料附件   
,ThreeAgreeFile	         as  	three_agree_file	            --三方协议/双方协议  
,ThreeAgreeFileDate	     as  	three_agree_file_date	        --归档时间           
,ThreeAgreeExpDate	     as  	three_agree_exp_date	        --失效时间           
,ThreeAgreeSign	         as  	three_agree_sign	            --签名               
,ThreeAgreeSignDate	     as  	three_agree_sign_date	        --时间               
,ThreeAgreeReMark	       as  	three_agree_remark	          --备注               
,ReNewAgreeFile	         as  	re_new_agree_file	            --续签三方协议/双方  
,ReNewAgreeFileDate	     as  	re_new_agree_file_date	      --归档时间           
,ReNewAgreeExpDate	     as  	re_new_agree_exp_date	        --失效时间           
,ReNewAgreeSign	         as  	re_new_agree_sign	            --签名               
,ReNewAgreeSignDate	     as  	re_new_agree_sign_date	      --时间               
,ReNewAgreeReMark	       as  	re_new_agree_remark	          --备注               
,AheadLeaveFile	         as  	ahead_leave_file	            --提前离项校方确认   
,AheadLeaveFileDate	     as  	ahead_leave_file_date	        --归档时间           
,AheadLeaveExpDate	     as  	ahead_leave_exp_date	        --失效时间           
,AheadLeaveSign	         as  	ahead_leave_sign	            --签名               
,AheadLeaveSignDate	     as  	ahead_leave_sign_date	        --时间               
,AheadLeaveReMark	       as  	ahead_leave_remark	          --备注               
,DeptLevel1Name	         as  	dept1_name	            --一级部门名称       
,Name	                   as  	dept2_name	                        --二级部门名称       
,dept3Name	             as  	dept3_name	                  --三级部门名称       
,DeptLevel4Name	         as  	dept4_name	            --四级部门名称       
,CompanyThesis	         as  	company_thesis	              --公司提供毕业论文 
,IsTrainee 				 as 	emp_type						--1 ，表示是实习生。0，表示是onsite人员
,PingYing 				 as 	display_name						--中文全拼
,RoomNo 				 as 	room_no							--房间号
,EnglishName 			 as 	english_name					--英文名
,TelShortNum 			 as 	tel_short_num					--电话短号
,TelLongNum 			 as 	tel_long_num					--电话长号
,Fax					 as 	fax								--传真
,SyncTime 				 as 	sync_time						--同步时间
,OfficePlace 			 as 	office_place					--研发HRCP新增了办公地点2
from V_PeronsInfo_ForDataMP
                                                             
