declare @ProPersonId  nvarchar(100)='73a998ed-fa77-4f62-a826-1a9a2a3dcb7c'
declare @coomgr  varchar(50)='liuyujing kf6850'
declare @Modifier  varchar(20)='lkf6850'
DECLARE @RecordId UNIQUEIDENTIFIER;
	SET @RecordId=NEWID();
	--SELECT @RecordId=ProjectPersonRecordId FROM dbo.ProjectPersonRecord WHERE ProjectPersonInfoId=@ProPersonId
    --更改状态后：增加ProjectControl_Person_Relation，controlid为空，propersonid人员主键，iscurrent 1
    --ProjectPersonEntry应该是不用改动。
    --ProjectPersonRecord建立备份表,RecordId使用新值  ---ProjectPersonRecord_History
    --ProjectPersonInfo建立备份表，增加唯一标识符；原表：PersonStatus修改，重置除CreateDate，CreateBy，ProjectPersonInfoId,Name,IdCard,Sex以外的其它值   --ProjectPersonInfo_History
    --MaterialFile建立备份表，,MaterialFileID使用新值   --MaterialFile_History	

    UPDATE ProjectControl_Person_Relation
    SET IsCurrent = 0,
        ModificationDate = GETDATE(),
        Modifier = @Modifier
    WHERE ProPersonId = @ProPersonId;


    INSERT INTO dbo.ProjectPersonRecord_History
    SELECT @RecordId,
           ProjectPersonInfoId,
           CreateDate,
           CreateBy,
           GETDATE(),
           @Modifier,
           DeleteFlag,
           CooDealBaseInfoSign,
           CooDealBaseInfoSignTime,
           CooMgrUploadEntryDataSign,
           CooMgrUploadEntryDataSignTime,
           DocAdminSureEntryOpinion,
           DocAdminSureEntryDataSign,
           DocAdminSureEntryDataSignTime,
           ProMgrSureReleaseDateSign,
           ProMgrSureReleaseDateSignTime,
           CooMgrUploadReleaseDataSign,
           CooMgrUploadReleaseDataSignTime,
           DocAdminSureReleaseOpinion,
           DocAdminSureReleaseDataSign,
           DocAdminSureReleaseDataSignTime,
           ByMonthAccount,
           CooMgrUploadEntryDataUrl,
           CooMgrUploadEntryOpinion,
           CooMgrUploadReleaseOpinion,
           NoMaterial,
           IsStopMaterial
    FROM ProjectPersonRecord
    WHERE ProjectPersonInfoId = @ProPersonId;

    UPDATE dbo.ProjectPersonRecord
    SET CooDealBaseInfoSign = NULL,
        CooDealBaseInfoSignTime = NULL,
        CooMgrUploadEntryDataSign = NULL,
        CooMgrUploadEntryDataSignTime = NULL,
        DocAdminSureEntryOpinion = NULL,
        DocAdminSureEntryDataSign = NULL,
        DocAdminSureEntryDataSignTime = NULL,
        ProMgrSureReleaseDateSign = NULL,
        ProMgrSureReleaseDateSignTime = NULL,
        CooMgrUploadReleaseDataSign = NULL,
        CooMgrUploadReleaseDataSignTime = NULL,
        DocAdminSureReleaseOpinion = NULL,
        DocAdminSureReleaseDataSign = NULL,
        DocAdminSureReleaseDataSignTime = NULL,
        ByMonthAccount = 0,
        CooMgrUploadEntryDataUrl = NULL,
        CooMgrUploadEntryOpinion = NULL,
        CooMgrUploadReleaseOpinion = NULL,
        NoMaterial = 1,
        IsStopMaterial = NULL
    WHERE ProjectPersonInfoId = @ProPersonId;

    DECLARE @NewPInfoId UNIQUEIDENTIFIER;
    SET @NewPInfoId = NEWID();

    INSERT INTO ProjectPersonInfo_History
    SELECT @NewPInfoId,
           *,@RecordId
    FROM dbo.ProjectPersonInfo
    WHERE ProjectPersonInfoId = @ProPersonId;

    UPDATE dbo.ProjectPersonInfo_History
    SET ModificationDate = GETDATE(),
        Modifier = @Modifier
    WHERE ProjectPersonInfoId = @NewPInfoId;

    UPDATE dbo.ProjectPersonInfo
    SET CooCompany = NULL,
        ProjectName = NULL,
        ProjectCode = NULL,
        DeptLevel2 = NULL,
        DeptCode2 = NULL,
        DeptLevel3 = NULL,
        DeptCode3 = NULL,
        ApplyType = '新申请',
        ProjectMgr = '',
        CooMgr = @coomgr,
        EntryDate = NULL,
        ExpiryDate = NULL,
        IsInField = 0,
        Area = NULL,
        ApplyEntryArea = NULL,
        LeaveDate = NULL,
        DirectMgr = NULL,
        EvaluateMgr = NULL,
        IsApplyId = NULL,
        ID = NULL,
        InfoSaveCheck = NULL,
        CheckResult = NULL,
        ModificationDate = NULL,
        Modifier = NULL,
        DeleteFlag = 0,
        CooType = NULL,
        IsOnDuty = 2,
        WorkPlace = NULL,
        PositionName = NULL,
        Native = NULL,
        Nation = NULL,
        PoliticalStatus = NULL,
        Marriage = NULL,
        Education = NULL,
        Major = NULL,
        BirthDay = NULL,
        Graduated = NULL,
        PhysicalExamination = NULL,
        PersonalSecrecyAgreement = NULL,
        ApplyRemark = NULL,
        ApplySign = NULL,
        ApplySignDate = NULL,
        DocCheckClose = NULL,
        DocCheckCloseRemark = NULL,
        DocCheckIsDone = NULL,
        DocCheckSign = NULL,
        DocCheckSignDate = NULL,
        PcLow = NULL,
        PcSpecial = NULL,
        BorrowStorage = NULL,
        InfoSafeRemark = NULL,
        InfoSafeIsDone = NULL,
        InfoSafeSign = NULL,
        InfoSafeSignDate = NULL,
        Pc = NULL,
        AssetMgrIsDone = NULL,
        AssetMgrRemark = NULL,
        AssetMgrSign = NULL,
        AssetMgrSignDate = NULL,
        DocMove = NULL,
        FileDoc = NULL,
        MaterialReturn = NULL,
        WorkCard = NULL,
        NotesDomainCancle = NULL,
        PdmCancle = NULL,
        PermissionCancleRemark = NULL,
        PermissionCancleSign = NULL,
        PermissionCancleSignDate = NULL,
        PermissionCancleIsDone = NULL,
        DoorCancle = NULL,
        DoorCancleRemark = NULL,
        DoorCancleIsDone = NULL,
        DoorCancleSign = NULL,
        DoorCancleSignDate = NULL,
        CardConfirm = NULL,
        CardConfirmStatus = NULL,
        CardConfirmIsDone = NULL,
        CardConfirmSign = NULL,
        CardConfirmSignDate = NULL,
        PdmConfirm = NULL,
        PdmConfirmStatus = NULL,
        PdmConfirmIsDone = NULL,
        PdmConfirmSign = NULL,
        PdmConfirmSignDate = NULL,
        PersonStatus = '在岗-外场',
        ArchiveTime = NULL,
        ReleaseTime = NULL,
        LeaveType = NULL,
        DirectorMgrSign = NULL,
        DirectorMgrSignDate = NULL,
        CooLeaveType = NULL,
        CooMgrSign = NULL,
        CooMgrSignDate = NULL,
        PositionLevel = NULL,
        ProjectType = NULL,
        AttendanceClass = NULL,
        IsTurnNext = NULL,
        IsFinishFile = NULL,
        IsWarn = NULL,
        FirstEntryDate = NULL,
        ProDirector = NULL,
        ReleaseType = NULL,
        ProMgrReleaseDate = NULL,
        AgreeStartDate = NULL,
        AgreeEndDate = NULL,
        PlanEndDate = NULL,
        DirectorCc = NULL,
        CooMgrCc = NULL,
        DocCheckCc = NULL,
        InfoSafeCc = NULL,
        AssetMgrCc = NULL,
        PermissionCancleCc = NULL,
        DoorCancleCc = NULL,
        ReceiptCc = NULL,
        LeaveFieldDate = NULL,
        ReleaseOpinion = NULL,
        PreStartDate = NULL,
        PreEndDate = NULL,
        IsSignLeave = NULL,
        DeptCode1 = NULL
    WHERE ProjectPersonInfoId = @ProPersonId;

    UPDATE dbo.ProcessFlow
    SET ApprovalId = @NewPInfoId,
        ModificationDate = GETDATE(),
        Modifier = @Modifier
    WHERE ApprovalId = @ProPersonId;

    UPDATE ProjectPersonEvaluate
    SET ProjectPersonInfoId = @NewPInfoId,
        ModificationDate = GETDATE(),
        Modifier = @Modifier
    WHERE ProjectPersonInfoId = @ProPersonId;

    INSERT INTO MaterialFile_History
    SELECT NEWID(),
           InterviewFile,
           InterviewFileDate,
           InterviewExpDate,
           InterviewSign,
           InterviewSignDate,
           InterviewRemark,
           WrittenFile,
           WrittenFileDate,
           WrittenExpDate,
           WrittenSign,
           WrittenSignDate,
           WrittenRemark,
           PersonalAgreeFile,
           PersonalSignDate,
           PersonalAgreeFileDate,
           PersonalAgreeExpDate,
           PersonalAgreeSign,
           PersonalAgreeSignDate,
           PersonalAgreeRemark,
           ItAgreeFile,
           ItAgreeFileDate,
           ItAgreeExpDate,
           ItAgreeSign,
           ItAgreeSignDate,
           ItAgreeRemark,
           PhysicalCopyFile,
           PhysicalCopyFileDate,
           PhysicalCopyExpDate,
           PhysicalCopySign,
           PhysicalCopySignDate,
           PhysicalCopyRemark,
           IdCardCopyFile,
           IdCardCopyFileDate,
           IdCardCopyExpDate,
           IdCardCopySign,
           IdCardCopySignDate,
           IdCardCopyRemark,
           CvCopyFile,
           CvCopyFileDate,
           CvCopyExpDate,
           CvCopySign,
           CvCopySignDate,
           CvCopyRemark,
           GraduateCopyFile,
           GraduateCopyFileDate,
           GraduateCopyExpDate,
           GraduateCopySign,
           GraduateCopySignDate,
           GraduateCopyRemark,
           LeaveAgreeFile,
           LeaveAgreeFileDate,
           LeaveAgreeExpDate,
           LeaveAgreeSign,
           LeaveAgreeSignDate,
           LeaveAgreeRemark,
           CreateBy,
           CreateDate,
           GETDATE(),
           @Modifier,
           DeleteFlag,
           PersonInfoId,
           PersonEntryId,
           AttachUrl,
           MaterialFileNo,
           CooOpinion,
           CooSign,
           CooSignDate,
           FileStatus,
           AttachLeaveUrl,
           ThreeAgreeFile,
           ThreeAgreeFileDate,
           ThreeAgreeExpDate,
           ThreeAgreeSign,
           ThreeAgreeSignDate,
           ThreeAgreeReMark,
           ReNewAgreeFile,
           ReNewAgreeFileDate,
           ReNewAgreeExpDate,
           ReNewAgreeSign,
           ReNewAgreeSignDate,
           ReNewAgreeReMark,
           AheadLeaveFile,
           AheadLeaveFileDate,
           AheadLeaveExpDate,
           AheadLeaveSign,
           AheadLeaveSignDate,
           AheadLeaveReMark,
           LeaveConfirmOpinion,
           LeaveConfirmSign,
           LeaveConfirmSignDate,
           LeaveCooSign,
           LeaveCooSignDate,
           EntryCooSign,
           EntryCooSignDate,
           Person,
           MaterialLeaveFileNo,
		   @RecordId
    FROM MaterialFile
    WHERE PersonInfoId = @ProPersonId;

    UPDATE MaterialFile
    SET InterviewFile = '归档',
        InterviewFileDate = NULL,
        InterviewExpDate = NULL,
        InterviewSign = NULL,
        InterviewSignDate = NULL,
        InterviewRemark = NULL,
        WrittenFile = '归档',
        WrittenFileDate = NULL,
        WrittenExpDate = NULL,
        WrittenSign = NULL,
        WrittenSignDate = NULL,
        WrittenRemark = NULL,
        PersonalAgreeFile = '归档',
        PersonalSignDate = NULL,
        PersonalAgreeFileDate = NULL,
        PersonalAgreeExpDate = NULL,
        PersonalAgreeSign = NULL,
        PersonalAgreeSignDate = NULL,
        PersonalAgreeRemark = NULL,
        ItAgreeFile = '归档',
        ItAgreeFileDate = NULL,
        ItAgreeExpDate = NULL,
        ItAgreeSign = NULL,
        ItAgreeSignDate = NULL,
        ItAgreeRemark = NULL,
        PhysicalCopyFile = '归档',
        PhysicalCopyFileDate = NULL,
        PhysicalCopyExpDate = NULL,
        PhysicalCopySign = NULL,
        PhysicalCopySignDate = NULL,
        PhysicalCopyRemark = NULL,
        IdCardCopyFile = '归档',
        IdCardCopyFileDate = NULL,
        IdCardCopyExpDate = NULL,
        IdCardCopySign = NULL,
        IdCardCopySignDate = NULL,
        IdCardCopyRemark = NULL,
        CvCopyFile = '归档',
        CvCopyFileDate = NULL,
        CvCopyExpDate = NULL,
        CvCopySign = NULL,
        CvCopySignDate = NULL,
        CvCopyRemark = NULL,
        GraduateCopyFile = '归档',
        GraduateCopyFileDate = NULL,
        GraduateCopyExpDate = NULL,
        GraduateCopySign = NULL,
        GraduateCopySignDate = NULL,
        GraduateCopyRemark = NULL,
        LeaveAgreeFile = '归档',
        LeaveAgreeFileDate = NULL,
        LeaveAgreeExpDate = NULL,
        LeaveAgreeSign = NULL,
        LeaveAgreeSignDate = NULL,
        LeaveAgreeRemark = NULL,
        ModificationDate = NULL,
        Modifier = NULL,
        DeleteFlag = 0,
        PersonEntryId = NULL,
        AttachUrl = NULL,
        MaterialFileNo = [dbo].[F_GetSerialProjectFileCode](),
        CooOpinion = NULL,
        CooSign = NULL,
        CooSignDate = NULL,
        FileStatus = NULL,
        AttachLeaveUrl = NULL,
        ThreeAgreeFile = NULL,
        ThreeAgreeFileDate = NULL,
        ThreeAgreeExpDate = NULL,
        ThreeAgreeSign = NULL,
        ThreeAgreeSignDate = NULL,
        ThreeAgreeReMark = NULL,
        ReNewAgreeFile = NULL,
        ReNewAgreeFileDate = NULL,
        ReNewAgreeExpDate = NULL,
        ReNewAgreeSign = NULL,
        ReNewAgreeSignDate = NULL,
        ReNewAgreeReMark = NULL,
        AheadLeaveFile = NULL,
        AheadLeaveFileDate = NULL,
        AheadLeaveExpDate = NULL,
        AheadLeaveSign = NULL,
        AheadLeaveSignDate = NULL,
        AheadLeaveReMark = NULL,
        LeaveConfirmOpinion = NULL,
        LeaveConfirmSign = NULL,
        LeaveConfirmSignDate = NULL,
        LeaveCooSign = NULL,
        LeaveCooSignDate = NULL,
        EntryCooSign = NULL,
        EntryCooSignDate = NULL,
        Person = @coomgr,
        MaterialLeaveFileNo = [dbo].[F_GetSerialProjectLeaveFileCode]()
    FROM MaterialFile
    WHERE PersonInfoId = @ProPersonId;